# Generated by Django 3.2 on 2022-06-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='graduate_date',
            new_name='end_date',
        ),
    ]
