# Generated by Django 3.2 on 2022-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_graduate_date_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='typo',
            field=models.IntegerField(choices=[(0, '位移'), (1, '称重'), (2, '应变'), (3, '流量'), (4, '测斜'), (5, 'GPS')], default='1', verbose_name='类型'),
            preserve_default=False,
        ),
    ]
