# Generated by Django 3.2 on 2022-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sensor_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
