# Generated by Django 3.2 on 2022-07-01 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_project_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(limit_choices_to={'urserinfo__name': 'cyeext'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_leader', to='web.userinfo', verbose_name='负责人'),
        ),
    ]
