# Generated by Django 3.2 on 2022-06-30 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的URL')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='URL别名')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('icon', models.CharField(max_length=32, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('access', models.ManyToManyField(blank=True, to='rbac.Access', verbose_name='所拥有的的权限')),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='null表示不是菜单；非null则为所属一级菜单的ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='所属一级菜单'),
        ),
        migrations.AddField(
            model_name='access',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='null表示自身即为所关联的二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_access', to='rbac.access', verbose_name='关联二级菜单id'),
        ),
    ]
